### PR TITLE
Modify profile fields

### PR DESCRIPTION
**Pull request by DavidWChen**
## Description
Covert Major Field to ManyToMany

Restrict Major to maximum of 2
Restrict Minor to maximum of 3

Added Search by Course
Added Search by Minor

## Pls do 
- [x] Tested and working
- [ ] Unit tests

### CODE REVIEW

**Comment by DavidWChen** [comment]
Don't bother reviewing yet.

**Comment by marktai** [comment]
should i review this now?

**Comment by marktai** [comment]
I'm going to assume this is in #69.  Can you close this PR if it is entirely in the other PR?

**Comment by DavidWChen** [comment]
Everything listed in this description is not in #69 . They're separated since I thought testing for limiting the fields should be separated from creating them

**Pull request closed without merging**
